# Prologue {-}

Good Morning! How are you doing? It's been great being part of the Analytical Community the last few years hasn't it? The excitement is everywhere about "big-data","data-science","MOOCs". I have been blown away by the talent being attracted into Analytics.One current trend is 'a shift from a desire to work for bigger name brand companies like Facebook or Google, to more mission-driven organizations attempting to make an impact on society. Whether it is curing cancer, conserving energy, tracking infectious disease or personalizing education, more data scientists are becoming interested in trying to make the world a  better place' [@nuggets].

My name is Edward Anderson and I like to play with financial models. For me it's always been about big ideas and models are a way to bring these ideas to life. Over the next 60 pages, please imagine yourself with me in the bright Spring of 2012 in the historic University City of Cambridge UK. I am a science-grad and Analyst at a financial services start-up business that had just completed a major acquisition. Our offices overlooking leafy Cambridge colleges are buzzing with energy as new colleagues join and information flows are gushing in all directions.In six weeks time we begin managing over €330m of customer accounts.

I was short of real-world experience but am about to become the Analytics Lead at our new Asset Management business. For the last three years I had been developing new models to understand how businesses operated. In-time I had the opportunity to work closely with a number of highly talented Executives and ultimately to my new promotion. I am full of new ideas but my to-do list is already too long and I am meeting everyday with new managers eager for support. Looking over my shoulder, what advice would you give to deliver impactful analytics on a tight time budget?

In the next forty-five minutes, you will walk out with my go-to-guide to using models to positively impact running a business!  My core message to you is that there are mutliple success factors and a kick-ass model is only one of them. As my CEO and mentor counselled me back in 2012 "the ops guys on the ground desperately need help. But the way to do this is a balancing act. You need to simulatenously listen to suggestions and keep people engaged whilst also driving discussions forward. By all means use models as a focal point".

Why am I writing now? Recently, I have been working with two open-source analytics tools/methods, "reproducible-research" and "R-studio".These belong to the Academic research community but were recently enhanced into a compelling commercial product and alternative to Microsoft. I will prove this to you by answering three questions, how do models help businesses meet strategic goals? What does a Microsoft analytics tool look like and what are its short-comings? What does an Open-Source alternative look like?

ok

