# (PART) Application {-}
# Research Methodology

My goal was to use a multiple linear regression model to accurately predict house prices. The starting point of my research was a sample data set from the website [kaggle](). The data contains property sales prices for transactions between May 2014 and May 2015 in King County USA which includes Seattle.

I started my research project by reviewing online literature on house price prediction. This "meta analysis" had two purposes:

- It helped select variables to include in the model 
- It added credibility to my findings if I incorporated and built on the empirical evidence of previous research studies

I performed significant data-enrichment activities. This involved API calls to the online repositories [Google]() and [Zillow](). My goal was to append to the data-set certain key variables identified in the "meta analysis".

I performed several formal model selection procedures. This involved:

- Variable selection
- Model fitting
- Diagnostics
- Selection between competing models

I evaluated model performance on a "hold-out sample" representing 20% of the original data-set. Model performance was evaluated through evaluating "out of sample" prediction accuracy.

## Meta Analysis/Literature Review

My data set from [Kaggle]() only included information on **micro variables**. These *micro variables* related to the intrinsic features of a property and its immediate environment. By contrast, *macro variables* were excluded. These relate to the "external environment" of the property (see examples below). 

By excluding macro variables, the parameter estimates of my model could be **biased**. For example, the data comes from the period from May 2014 to May 2015 when the external environment in the US was relatively stable. This means that the level of noise in the data could be artificially low and the explanatory power of micro variables overstated.

To mitigate this risk I performed a quick online literature search and identified micro variables which previous research studies have found to be significant predictors of property price. I have included these variables as the starting point of the model selection process in Section \@ref(Classical). This should lead as much overlap as possible between my model and previous studies and stops me relying 100% on a statistical model selection procedure which is vulnerable to bias.

In Section \@ref(CompSci), I take a more pro-active approach to dealing with potential bias. I use the results of a data-enrichment exercise to extend my original data-set to include **macro variables**. Furthermore these macro variables are exactly those which previous studies found to be significant predictors of property prices. 

#### Micro variable Examples

- Building features
- Interior Layout and Size
- Quality of fixture and fittings

#### Macro variable Examples

- Nearby amenities
- Cost of mortgage borrowing in the area
- unemployment levels in the job market
- demographics 

#### Results of online search

The table below shoes the micro-variables identified online, the reference article and the matching field in the database. Article 1 is [@galati2011macro], Article 2 is [@candas2015], Website 1 is [@rightmove]


|Micro-variable         | Reference | Data-Set Field  |
|-----------------------|:---------:|-----------------|
|Year of Construction   | Article 1 |Construction Year|
|Size of Living Room    | Article 1 |Living Space     |
|Presence of Garage     | Article 1 |                 |
|Presence of Garden     | Article 1 |                 |
|Type of House          | Article 1 |Number of Floors |
|Large City vs not large| Article 1 |Seattle ZipCode  |
|Degree of Urbanization | Article 1 |                 |
|Floor No               | Article 2 |Floors           |
|Heating System         | Article 2 |Renovation Year  |
|Earthquake Zone        | Article 2 |                 |
|Rental Value           | Article 2 |                 |
|Land Value             | Article 2 |                 |
|Parcel Area            | Article 2 |Total Area       |
|Zoning                 | Article 2 |Zipcode          |
|Proximity to Amenities | Website 1 |                 |
|Number of Bedrooms     | Website 1 |Bedrooms         |
|Number of Bathrooms    | Website 1 |Bathrooms        |
|Age of Building        | Website 1 |                 |
|Condition of Interior  | Website 1 |Condition/Grade  |



# Computer Science Approach {#CompSci}

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two
